# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityimage',
            name='image',
            field=models.ImageField(upload_to='images/commodity/%Y/%m/%d'),
        ),
    ]
