# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='quota',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='stock',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='leader',
            name='successful_times',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='membership_order_to_commodities',
            name='quantity',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(max_length=10),
        ),
    ]
