# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distributer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='console.Distributer'),
            preserve_default=False,
        ),
    ]
