# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_auto_20160309_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributer',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
    ]
