# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_batch_distributers'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributer',
            name='location',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='batch',
            name='distributers',
        ),
        migrations.AddField(
            model_name='batch',
            name='distributers',
            field=models.ManyToManyField(to='console.Distributer'),
        ),
    ]
