# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_auto_20160310_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='console.Batch'),
            preserve_default=False,
        ),
    ]
