# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0005_customer_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodityinorder',
            name='price',
        ),
    ]
