# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0007_auto_20160408_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='share_img_url',
        ),
        migrations.AddField(
            model_name='batch',
            name='share_img',
            field=models.ImageField(blank=True, upload_to='shareImg'),
        ),
    ]
