# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0008_auto_20160408_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityinorder',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.CommodityInBatch'),
        ),
        migrations.AlterField(
            model_name='order',
            name='commodities',
            field=models.ManyToManyField(through='console.CommodityInOrder', to='console.CommodityInBatch'),
        ),
    ]
