# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0010_auto_20160408_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prepay_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
