# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0011_order_prepay_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
