# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0012_order_total_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityinbatch',
            name='unit_price',
            field=models.IntegerField(max_length=10),
        ),
    ]
