# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20160530_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
