# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20160615_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobuser',
            name='parent',
        ),
    ]
