# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20160602_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('dead_time', models.DateTimeField()),
                ('arrived_time', models.DateTimeField()),
                ('status', models.IntegerField(max_length=11)),
                ('card_title', models.CharField(max_length=100)),
                ('card_desc', models.CharField(max_length=255)),
                ('card_icon', models.ImageField(blank=True, upload_to='images/card_icon/%Y/%m/%d')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('dispatchers', models.ManyToManyField(to='business.Dispatcher')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('status', models.IntegerField(max_length=10)),
                ('prepay_id', models.CharField(max_length=200)),
                ('freight', models.IntegerField(max_length=11)),
                ('total_fee', models.IntegerField(max_length=11)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('bulk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Bulk')),
                ('dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Dispatcher')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('unit_price', models.IntegerField(max_length=11)),
                ('market_price', models.IntegerField(max_length=11)),
                ('spec', models.CharField(max_length=100)),
                ('spec_details', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='images/product/%Y/%m/%d')),
                ('is_snapshot', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/product_details/%Y/%m/%d')),
                ('plain', models.TextField()),
                ('seq', models.IntegerField(max_length=11)),
                ('is_snapshot', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='business.Goods', to='business.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.User'),
        ),
        migrations.AddField(
            model_name='goods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Order'),
        ),
        migrations.AddField(
            model_name='goods',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Product'),
        ),
        migrations.AddField(
            model_name='bulk',
            name='products',
            field=models.ManyToManyField(to='business.Product'),
        ),
        migrations.AddField(
            model_name='bulk',
            name='reseller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Reseller'),
        ),
    ]
