# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20160602_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'Goods', 'verbose_name_plural': 'Goods'},
        ),
        migrations.AlterModelOptions(
            name='productdetails',
            options={'verbose_name': 'Product details', 'verbose_name_plural': 'Product details'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='details',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='spec_details',
            new_name='spec_desc',
        ),
    ]
