# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_goods_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedProductHistory',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(max_length=11)),
                ('spec', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'view_history_purchased_products',
                'managed': False,
            },
        ),
    ]
