# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_purchasedproducthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatcher',
            name='closing_time',
            field=models.IntegerField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispatcher',
            name='opening_time',
            field=models.IntegerField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
