# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_auto_20160606_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mob', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
    ]
