# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_remove_goods_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recent_obtain_mob',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='recent_obtain_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
