# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_auto_20160607_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulk',
            name='details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
