# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_bulk_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='obtain_mob',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='obtain_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
