# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_auto_20160607_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulk',
            name='location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
