# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_bulk_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='obtain_mob',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='obtain_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
