# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_auto_20160613_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='prepay_id',
        ),
    ]
