# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_remove_order_prepay_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
