# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_order_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, max_length=11),
        ),
    ]
