# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_user_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_party_order_id', models.CharField(max_length=200)),
                ('third_party_fee', models.IntegerField(default=0)),
                ('balance_fee', models.IntegerField(default=0)),
                ('use_balance', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.Order')),
            ],
        ),
    ]
