# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_payrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('hot_bulks', models.ManyToManyField(to='business.Bulk')),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('seq', models.IntegerField(max_length=11)),
                ('stick', models.BooleanField(default=False)),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Exhibit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/card_icon/%Y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='exhibit',
            name='hot_products',
            field=models.ManyToManyField(through='business.ExhibitedProduct', to='business.Product'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='slides',
            field=models.ManyToManyField(to='business.Slide'),
        ),
    ]
