# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_auto_20160620_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
