# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_slide_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitedproduct',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exhibitedproduct',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
