# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 08:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_auto_20160620_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='create_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 20, 8, 9, 2, 709498, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
