# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_slide_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='seq',
            field=models.IntegerField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
