# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_slide_seq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulk',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='bulk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='business.Bulk'),
            preserve_default=False,
        ),
    ]
