# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_auto_20160620_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
