# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0030_auto_20160621_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitedproduct',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='exhibitedproduct',
            name='title',
        ),
        migrations.AddField(
            model_name='exhibitedproduct',
            name='cover',
            field=models.ImageField(default='', upload_to='images/card_icon/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
