# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0032_auto_20160621_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/dish/%Y/%m/%d')),
                ('status', models.IntegerField(max_length=11)),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DishDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/dish_details/%Y/%m/%d')),
                ('plain', models.TextField()),
                ('seq', models.IntegerField(max_length=11)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Dish')),
            ],
            options={
                'verbose_name': 'Dish details',
                'verbose_name_plural': 'Dish details',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('seq', models.IntegerField(max_length=11)),
                ('quantity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('dish_num', models.IntegerField(default=0, max_length=11)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/recipe/%Y/%m/%d')),
                ('status', models.IntegerField(max_length=11)),
                ('tag', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/step/%Y/%m/%d')),
                ('plain', models.TextField()),
                ('seq', models.IntegerField(max_length=11)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Recipe')),
            ],
            options={
                'verbose_name': 'Step details',
                'verbose_name_plural': 'Step details',
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='exhibitedproduct',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/exhibited_product/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='images/slide/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tips',
            field=models.ManyToManyField(to='business.Tip'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.User'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Recipe'),
        ),
        migrations.AddField(
            model_name='dish',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.Recipe'),
        ),
        migrations.AddField(
            model_name='dish',
            name='tips',
            field=models.ManyToManyField(to='business.Tip'),
        ),
        migrations.AddField(
            model_name='dish',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.User'),
        ),
    ]
