# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0033_auto_20160621_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='dish_num',
        ),
    ]
