# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0035_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='cover',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.Image'),
        ),
    ]
