# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 11:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0037_auto_20160621_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='create_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 21, 11, 4, 14, 115764, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
