# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0038_image_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='dishdetails',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='step',
            name='image',
        ),
    ]
