# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0039_auto_20160621_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AlterField(
            model_name='image',
            name='md5',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
