# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0041_auto_20160621_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='tag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
