# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0044_auto_20160622_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
