# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0045_auto_20160623_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dishdetails',
            name='plain',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='plain',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='plain',
            field=models.TextField(blank=True),
        ),
    ]
