# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0046_auto_20160623_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeExhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('slides', models.ManyToManyField(to='business.Slide')),
            ],
        ),
    ]
