# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0047_recipeexhibit'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='key',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
    ]
