# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0050_user_recent_dispatcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulk',
            name='receive_mode',
            field=models.IntegerField(default=2, max_length=11),
        ),
    ]
