# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0053_exhibitedproduct_cover_3x'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
