# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0057_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulk',
            name='category',
        ),
    ]
