# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0060_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkSummary',
            fields=[
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='business.Product')),
                ('total_price', models.IntegerField(max_length=11)),
                ('quantity', models.IntegerField(max_length=11)),
                ('spec', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'view_bulk_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('mob', models.CharField(blank=True, max_length=100, null=True)),
                ('opening_time', models.IntegerField(max_length=11)),
                ('closing_time', models.IntegerField(max_length=11)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Reseller')),
            ],
        ),
    ]
