# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0061_bulksummary_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulk',
            name='dispatchers',
        ),
        migrations.AddField(
            model_name='bulk',
            name='storages',
            field=models.ManyToManyField(to='business.Storage'),
        ),
    ]
