# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0062_auto_20160816_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dispatcher',
        ),
        migrations.RemoveField(
            model_name='user',
            name='recent_dispatcher',
        ),
        migrations.AddField(
            model_name='order',
            name='storage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='business.Storage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='recent_storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.Storage'),
        ),
    ]
