# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0064_auto_20160816_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='closing_time',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='opening_time',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
    ]
