# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 06:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0065_auto_20160817_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulk',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 17, 6, 37, 0, 983132, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
