# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0066_bulk_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Storage'),
        ),
    ]
