# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0068_auto_20160829_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='receive_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='mob',
            new_name='receive_mob',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='receive_name',
        ),
    ]
