# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0071_order_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_snapshot',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='is_snapshot',
        ),
    ]
