# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0072_auto_20160905_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='limit',
            field=models.IntegerField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, max_length=11),
        ),
    ]
