# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0073_auto_20160905_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.User'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchased',
            field=models.IntegerField(default=0, max_length=11),
        ),
    ]
