# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-08 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0074_auto_20160905_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='state',
            field=models.IntegerField(default=0, max_length=11),
        ),
        migrations.AlterField(
            model_name='product',
            name='bulk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.Bulk'),
        ),
    ]
