# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-12 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0075_auto_20160908_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bulk',
        ),
        migrations.AddField(
            model_name='bulk',
            name='products',
            field=models.ManyToManyField(to='business.Product'),
        ),
    ]
