# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-23 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0076_auto_20160912_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=0, max_length=11)),
            ],
        ),
        migrations.RemoveField(
            model_name='bulk',
            name='products',
        ),
        migrations.AddField(
            model_name='bulkproduct',
            name='bulk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Bulk'),
        ),
        migrations.AddField(
            model_name='bulkproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Product'),
        ),
    ]
