# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-23 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0077_auto_20160923_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulk',
            name='products',
            field=models.ManyToManyField(through='business.BulkProduct', to='business.Product'),
        ),
    ]
