# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-23 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0078_bulk_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk_card_title_template', models.CharField(max_length=200)),
                ('bulk_card_desc_template', models.CharField(max_length=200)),
            ],
        ),
    ]
