# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-23 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0079_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='order_card_desc_template',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='order_card_title_template',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
