# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-26 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0080_auto_20160923_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='bulk_card_desc_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='bulk_card_title_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='order_card_desc_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='order_card_title_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
