# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0081_auto_20160926_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulk',
            name='arrived_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
