# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='commodityinbatch',
            name='quota',
        ),
        migrations.RemoveField(
            model_name='distributer',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='distributer',
            name='nick_name',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='nick_name',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='successful_times',
        ),
    ]
