# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20160524_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='detail',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
