# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_batch_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodityimage',
            name='commodity',
        ),
        migrations.AddField(
            model_name='commodity',
            name='image',
            field=models.ImageField(default='', upload_to='images/commodity/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CommodityImage',
        ),
    ]
