# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20160524_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=20, unique=True)),
                ('passwd', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('id_wechat', models.CharField(max_length=200, unique=True)),
                ('avatar', models.CharField(max_length=200)),
            ],
        ),
    ]
