# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 17:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 24, 17, 9, 34, 258792)),
            preserve_default=False,
        ),
    ]
