# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_remove_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passwd',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='123456', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
